### ISSUE TITLE
User endpoints

### ISSUE THREAD

**Issue by edvardvb** [askbk/inmarket-backend#14]
Certain endpoints must be added or modified to allow for several use cases.

- [x] Get all users (with filter). Used for searching for specific users.
- [x] Get my connections. Used for showing a list of my entire network.
- [x] Get awaiting connections, both sent and received. Used for showing pending requests.
- [x] When fetching a user (or several), the object must contain whether or not the current user is connected to that user ("connection status"). We need this to know whether a listing should display buttons for activites, connection requests, etc.
  - Alternative: Fetch connection status for a set of users separately, after relevant users are fetched.
  - Alternative: Separate endpoints for connected users, users with pending requests, and not-yet-connected users.
- [ ] When fetching a user, the object should contain their star rating.

**Comment by askbk** [comment]
For now, we only have an endpoint for getting received contact requests, not sent.
This information is however included in connectionStatus property of fetched users, so we should be able to make due.

Star rating will be implemented properly at a later date.
