### ISSUE TITLE
Sending a contact request does not work

### ISSUE THREAD

**Issue by edvardvb** [askbk/inmarket-backend#15]
Sending a contact request currently returns the following:

![image](https://user-images.githubusercontent.com/8725291/58038007-1bb46f80-7b2f-11e9-9f27-586f549ef6af.png)

`Table "inmarket_db.contacts" doesn't exist`

**Comment by askbk** [comment]
Not sure what this could be. Weird that the Contacts table isn't created for you.

**Comment by edvardvb** [comment]
![image](https://user-images.githubusercontent.com/8725291/58080160-efdacd80-7bb2-11e9-8607-0a411e3b2749.png)

This is the output from startup in docker-compose. Maybe the table is dropped but never created again?

**Comment by askbk** [comment]
OK, I see what's going on. You need to drop some of the tables. Specifically, those pertaining to conversation. This is because some models have been renamed, meaning that the old tables aren't being dropped because sequelize no longer knows they exist.

**Comment by edvardvb** [comment]
Yup, seems to work now :)
