### ISSUE TITLE
Backend vil ikke starte

### ISSUE THREAD

**Issue by Z4F1** [askbk/inmarket-backend#30]
Får ikke backend til å starte opp. Ender alltid opp med denne error meldingen.

```
node_1      | [nodemon] 1.18.9
node_1      | [nodemon] to restart at any time, enter `rs`
node_1      | [nodemon] watching: /usr/app/src/**/*
node_1      | [nodemon] starting `node src/server.js`
node_1      | internal/modules/cjs/loader.js:751
node_1      |   return process.dlopen(module, path.toNamespacedPath(filename));
node_1      |                  ^
node_1      | 
node_1      | Error: /usr/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node: invalid ELF header
node_1      |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:751:18)
node_1      |     at Module.load (internal/modules/cjs/loader.js:620:32)
node_1      |     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
node_1      |     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
node_1      |     at Module.require (internal/modules/cjs/loader.js:658:17)
node_1      |     at require (internal/modules/cjs/helpers.js:22:18)
node_1      |     at Object.<anonymous> (/usr/app/node_modules/bcrypt/bcrypt.js:6:16)
node_1      |     at Module._compile (internal/modules/cjs/loader.js:722:30)
node_1      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
node_1      |     at Module.load (internal/modules/cjs/loader.js:620:32)
node_1      |     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
node_1      |     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
node_1      |     at Module.require (internal/modules/cjs/loader.js:658:17)
node_1      |     at require (internal/modules/cjs/helpers.js:22:18)
node_1      |     at new Auth (/usr/app/src/components/auth/auth.js:10:23)
node_1      |     at Object.<anonymous> (/usr/app/src/sequelize.js:122:14)
node_1      |     at Module._compile (internal/modules/cjs/loader.js:722:30)
node_1      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
node_1      |     at Module.load (internal/modules/cjs/loader.js:620:32)
node_1      |     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
node_1      |     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
node_1      |     at Module.require (internal/modules/cjs/loader.js:658:17)
node_1      | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by askbk** [comment]
Dette skjer typisk hvis bcrypt (et av bibliotekene vi bruker) blir kompilert på et annet operativsystem enn det blir kjørt på (Linux).
Har du kjørt `npm install`?

**Comment by Z4F1** [comment]
Ja har gjort det.
Jeg bruker forresten Mac

**Comment by askbk** [comment]
kunne du prøvd å bytte ut 
`command: npm start` i docker-compose.yaml med
`command: sh -c 'apt-get update && apt-get install -y build-essential && apt-get install -y python && npm install && npm start'`

**Comment by Z4F1** [comment]
Får fortsatt samme error

**Comment by Z4F1** [comment]
Søkte litt rundt på nettet og fant ut at jeg måtte endre på volumes.

```yaml
volumes:
            - '.:/usr/app'
            - /usr/app/node_modules
```
Alt funker. Får gått inn på localhost/api/test, men får error over databasen nå. 

```
node_1      | Unable to connect to database: { SequelizeConnectionError: (conn=-1, no: 1130, SQLState: HY000) Host '172.18.0.3
' is not allowed to connect to this MariaDB server
```

**Comment by askbk** [comment]
Hmm, kan ikke skjønne hvordan det skal påvirke tilkoblingen til databasen

**Comment by Z4F1** [comment]
Når jeg kjører `docker exec -it inmarket-backend_database_1 bash` og prøver å logge inn med `mysql -u ask -p` så står det `ERROR 1045 (28000): Access denied for user 'ask'@'localhost' (using password: YES)`.

**Comment by askbk** [comment]
brukte du passordet 123?

**Comment by Z4F1** [comment]
Jepp. Det funket før, men nå sluttet det å funke. Prøvde å laste ned repositorien på nytt, men det hjalp ikke.

**Comment by Z4F1** [comment]
Jeg tror jeg fant ut av det. Måtte logge inn med root og lage en ask bruker med passordet 123 og deretter lage en database inmarket_db. Nå ser det ut som det funker.

**Comment by askbk** [comment]
Ok, da skjønner jeg hvorfor akkurat det problemet oppstod: jeg fjernet noen SQL-filer, men tenkte ikke på at da blir ikke databasen opprettet noe sted. skal fikse.

**Comment by Z4F1** [comment]
Supert. Alltid gøy å debugge ;))

**Comment by Z4F1** [comment]
Da bare closer jeg denne.

**Comment by askbk** [comment]
Funker hele backend nå altså? :open_mouth: I så fall: lag en PR med endringene du gjorde som fikk det til å virke, så skal jeg dobbeltsjekke at det da også virker i produksjonsmiljøet

**Comment by Z4F1** [comment]
Eneste jeg måtte endre var `docker-compose.yaml` hvor jeg under node, måtte legge til en volume 
`- /usr/app/node_modules`

Ellers var det å lage en bruker til databasen, men det fikset vel du igjen nå eller?

**Comment by askbk** [comment]
Tror det, men supert hvis du kan teste at det faktisk ble fikset. Pushet direkte til development.
Husk å kjøre med `docker-compose up --build` slik at brukeren du lagde manuelt ikke er der fortsatt :100:

**Comment by Z4F1** [comment]
Ja alt funket nå. Så det eneste som jeg trengte var den volume'en under node

**Comment by Z4F1** [comment]
Har du testet å legge til den volume'en hos deg?

**Comment by askbk** [comment]
Virket fint hos meg!
